---
# ansible-playbook /etc/ansible/playbooks/cassandra3x/role_provisioning_cassandra3x_enable_start.yml --extra-vars "target=ansible_inventory_hosts"
- hosts: "{{ target | default('FAIL') }}"
  gather_facts: true
  any_errors_fatal: true
  roles:
    - cassandra3x_provision_enable_start
