---
- name: install jmxremote.password
  template:
    src: jmxremote.password
    dest: "{{ cassandra3x_jmxremote_password }}"
    owner: "{{ cassandra3x_linux_user }}"
    group: "{{ cassandra3x_linux_group }}"    
    mode: "{{ cassandra3x_cassandra_sec_file_mode }}"
